Created registration page
longvulam/fetch-webapp pull request #4
Opened 2022-03-08 08:45 UTC by jason-rivera

2022-03-08 20:01 UTC, longvulam requested changes
Please merge with main then re-push.
The other branch needs to wait for this to be merged before doing the same so you won't run into conflicts again.
You can try to branch from your current working branches for you next feature to avoid that.

2022-03-09 00:43 UTC, jason-rivera commented
> Owner

Thanks for the tip!

2022-03-09 00:53 UTC, IzzySato approved these changes

2022-03-09 00:54 UTC, IzzySato approved these changes

2022-03-09 00:55 UTC, IzzySato approved these changes

2022-03-09 00:55 UTC, IzzySato approved these changes

2022-03-09 00:58 UTC, jason-rivera reviewed
done

2022-03-09 01:24 UTC, longvulam approved these changes

2022-03-09 01:24 UTC, merged